"""
My New Filter — Generated by Plugin Builder
"""
from __future__ import annotations
from PIL import Image, ImageOps, ImageFilter
from app.plugin_api import Plugin, Setting


class MyNewFilterPlugin(Plugin):
    name = "My New Filter"
    version = "1.0.0"

    def apply(self, img: Image.Image, **kwargs) -> Image.Image:
        # --- USER CODE START ---
        Test
        # --- USER CODE END ---

    def register(self, ctx) -> None:
        ctx.register_filter(
            self.name,
            self.apply,
            category="Filters",
            settings=[],
        )
