"""
plugin_builder.py - A tool to generate new plugin files from within the app.
"""

from __future__ import annotations

import os
import textwrap
from PIL import Image
from app.plugin_api import Plugin, Setting


class PluginBuilder(Plugin):
    name = "Plugin Builder"
    version = "1.4.0"

    def apply(
        self,
        img: Image.Image,
        *,
        new_plugin_name: str = "My New Filter",
        category: str = "Custom",
        code_logic: str = "",
        save_trigger: bool = False,
    ) -> Image.Image:

        if save_trigger:
            # 1. Clean up the plugin name for the filename
            safe_name = "".join(
                c if (c.isalnum() or c == "_") else "_"
                for c in new_plugin_name.strip().lower().replace(" ", "_")
            ).strip("_")

            if not safe_name or safe_name == "plugin_builder":
                print("Invalid plugin name — choose a different name.")
                return img

            filename = f"{safe_name}.py"

            # 2. Path to the Plugins folder (same directory as this file)
            current_dir = os.path.dirname(os.path.abspath(__file__))
            file_path = os.path.join(current_dir, filename)

            # 3. Indent the user's code to fit inside the apply() method
            indented_logic = textwrap.indent(code_logic.strip(), "        ")

            # 4. Derive a valid class name from the plugin name
            class_name = (
                "".join(c for c in new_plugin_name.title() if c.isalnum())
                or "GenPlugin"
            )

            # 5. Write the plugin file from the template
            plugin_template = (
                f'"""\n'
                f'{new_plugin_name} — Generated by Plugin Builder\n'
                f'"""\n'
                f'from __future__ import annotations\n'
                f'from PIL import Image, ImageOps, ImageFilter\n'
                f'from app.plugin_api import Plugin, Setting\n'
                f'\n'
                f'\n'
                f'class {class_name}Plugin(Plugin):\n'
                f'    name = "{new_plugin_name}"\n'
                f'    version = "1.0.0"\n'
                f'\n'
                f'    def apply(self, img: Image.Image, **kwargs) -> Image.Image:\n'
                f'        # --- USER CODE START ---\n'
                f'{indented_logic}\n'
                f'        # --- USER CODE END ---\n'
                f'\n'
                f'    def register(self, ctx) -> None:\n'
                f'        ctx.register_filter(\n'
                f'            self.name,\n'
                f'            self.apply,\n'
                f'            category="{category}",\n'
                f'            settings=[],\n'
                f'        )\n'
            )

            try:
                with open(file_path, "w", encoding="utf-8") as f:
                    f.write(plugin_template)
                print(f"✅ Saved: {file_path}")
            except Exception as e:
                print(f"❌ Save failed: {e}")

        return img

    def register(self, ctx) -> None:
        default_code = (
            "# Write your plugin logic here.\n"
            "# 'img' is the input PIL Image — return the modified image.\n"
            "img = img.convert('RGB')\n"
            "img = ImageOps.posterize(img, 4)\n"
            "return img"
        )

        ctx.register_filter(
            "Plugin Builder",
            self.apply,
            category="Development",
            settings=[
                Setting(
                    name="new_plugin_name",
                    type="string",
                    default="My New Filter",
                    label="Plugin Name",
                ),
                Setting(
                    name="category",
                    type="choice",
                    default="Custom",
                    label="Category",
                    choices=["Filters", "Generators", "Stylize", "Custom"],
                ),
                Setting(
                    name="code_logic",
                    type="text",       # multiline — "text" vs "string" (single line)
                    default=default_code,
                    label="Python Logic  (img → return img)",
                    rows=20,           # tall enough to see a full function
                    monospace=True,    # fixed-width font, left-aligned like a code editor
                ),
                Setting(
                    name="save_trigger",
                    type="bool",
                    default=False,
                    label="💾 Save Plugin  (toggle ON to save)",
                ),
            ],
        )